### ISSUE TITLE
Can we use Incremental View Maintenance (IVM)  to maintain materialized views in pg-10.5?

### ISSUE THREAD

**Issue by Aken-Gan** [sraoss/pgsql-ivm#123]
hello， can we use Incremental View Maintenance (IVM) to maintain materialized views，and how to install ivm?

**Comment by yugo-n** [comment]
To use IVM, you have to download the codes from this repository, or apply the patch submitted in the following post to PostgreSQL code. In both cases, you need to compile it from the source code.

https://www.postgresql.org/message-id/20201222215136.39a3736a948161fb490dbc75%40sraoss.co.jp

However, we are implementing IVM on master branch of PostgreSQL targetting 14, so  you cannot apply the patch to PostgreSQL 10.5, unfortunately.

**Comment by yugo-n** [comment]
If you just want to test IVM, you can use a docker image of PostgreSQL with IVM.
https://hub.docker.com/r/yugonagata/postgresql-ivm

**Comment by Aken-Gan** [comment]
thanks for Yugo Nagata answer ，if I want to use for production env to support application，how to install IVM in pg-10.5 ?


| |
Aken
|
|
akengan@yeah.net
|
签名由网易邮箱大师定制
On 1/4/2021 11:20，Yugo Nagata<notifications@github.com> wrote：

If you just want to test IVM, you can use a docker image of PostgreSQL with IVM.
https://hub.docker.com/r/yugonagata/postgresql-ivm

**Comment by yugo-n** [comment]
>thanks for Yugo Nagata answer ，if I want to use for production env to support application，how to install IVM in pg-10.5 ?

Unfortunately, there is no way to install IVM into production environments because this is developed as a new feature of PostgreSQL core rather than as an extension module. So, if you want to use this, as I mentioned it, you need to apply the patch to PostgreSQL code of 10.5 and re-compile it.  However, you have to modify the patch by your self because the patch is created for the latest code and not applicable to 10.5.

**Comment by Aken-Gan** [comment]
Thank you for your prompt reply.


| |
Aken
|
|
akengan@yeah.net
|
签名由网易邮箱大师定制
On 1/4/2021 17:49，Yugo Nagata<notifications@github.com> wrote：

thanks for Yugo Nagata answer ，if I want to use for production env to support application，how to install IVM in pg-10.5 ?

Unfortunately, there is no way to install IVM into production environments because this is developed as a new feature of PostgreSQL core rather than as an extension module. So, if you want to use this, as I mentioned it, you need to apply the patch to PostgreSQL code of 10.5 and re-compile it. However, you have to modify the patch by your self because the patch is created for the latest code and not applicable to 10.5.
