### ISSUE TITLE
pg_dump/restore support

### ISSUE THREAD

**Issue by thoshiai** [sraoss/pgsql-ivm#17]
Currently, CREATE INCREMENTAL MATERIALIZED VIEW statement is not supported by pg_dump.
If we dump matview with IVM, it will become normal  materialiaed view(not IVM).

**Comment by tatsuo-ishii** [comment]
This should be fixed. Added to the open items list.
https://github.com/sraoss/pgsql-ivm/wiki/Open-items-for-the-first-cut-of-IVM-patches
