### ISSUE TITLE
UPDATE to base table causes an ERROR

### ISSUE THREAD

**Issue by tatsuo-ishii** [sraoss/pgsql-ivm#20]
CREATE INCREMENTAL MATERIALIZED VIEW mv3 AS SELECT min(abalance),max(abalance),avg(abalance) FROM pgbench_accounts;
test=# UPDATE pgbench_accounts SET abalance = abalance + 10 WHERE aid = 10853;
ERROR:  syntax error at end of input
LINE 1: ...blic.mv3 AS mv USING t WHERE mv.ctid = t.ctid AND for_dlt ) 
                                                                       ^
QUERY:  WITH t AS (  SELECT diff.__ivm_count__,          diff.min, diff.__ivm_count_min__, diff.max, diff.__ivm_count_max__, diff.avg, diff.__ivm_sum_avg__, diff.__ivm_count_avg__,         (diff.__ivm_count__ = mv.__ivm_count__) AS for_dlt,          mv.ctid  FROM public.mv3 AS mv, pg_temp_3.pg_temp_16548 AS diff WHERE (1) = (1)), updt AS (  UPDATE public.mv3 AS mv SET __ivm_count__ = mv.__ivm_count__ - t.__ivm_count__,                      min = CASE WHEN mv.__ivm_count_min__ = t.__ivm_count_min__ THEN NULL ELSE mv.min END, __ivm_count_min__ = mv.__ivm_count_min__ - t.__ivm_count_min__, max = CASE WHEN mv.__ivm_count_max__ = t.__ivm_count_max__ THEN NULL ELSE mv.max END, __ivm_count_max__ = mv.__ivm_count_max__ - t.__ivm_count_max__, avg = CASE WHEN mv.__ivm_count_avg__ = t.__ivm_count_avg__ THEN NULL ELSE (COALESCE(mv.__ivm_sum_avg__,0) - COALESCE(t.__ivm_sum_avg__, 0))::numeric / (mv.__ivm_count_avg__ - t.__ivm_count_avg__) END, __ivm_sum_avg__ = COALESCE(mv.__ivm_sum_avg__,0) - COALESCE(t.__ivm_sum_avg__, 0), __ivm_count_avg__ = mv.__ivm_count_avg__ - t.__ivm_count_avg__  FROM t WHERE mv.ctid = t.ctid AND NOT for_dlt   RETURNING mv.ctid, (mv.min >= t.min OR mv.max <= t.max) AS recalc), dlt AS (  DELETE FROM public.mv3 AS mv USING t WHERE mv.ctid = t.ctid AND for_dlt )

**Comment by yugo-n** [comment]
I'm working on this

**Comment by tatsuo-ishii** [comment]
I confirmed this has been fixed.
