### ISSUE TITLE
Aggregate function support

### ISSUE THREAD

**Issue by thoshiai** [sraoss/pgsql-ivm#3]
Currently, aggreagate function is not supported by IVM.
For example, sum(), count() and more.

**Comment by thoshiai** [comment]
The sum() and count() aggregation function supported in  commit a798f20b615a03930e529b2afdbb5ca7e26a2ec8.

**Comment by thoshiai** [comment]
avg() aggregation function supported in commit 2cbef84479cb1737c29aa0875dbf8a09dedc5f47.

Currently, min() and max() function have not been supported yet.

And some option have not been supported yet 
e.g. HAVING and FILTER , GROUPING SET, etc...

**Comment by thoshiai** [comment]
IVM’s restriction:
* Aggregate functions must occur only as the outermost part of the expression like as Fast refresh of Oracle . That is, aggregates such as AVG(AVG(x)) or AVG(x)+ AVG(x) are not allowed.

**Comment by salacr** [comment]
Hi 
what about array_agg / json_agg / jsonb_agg it would be really useful in my opinion.
Our use case.
We have entity / entity2tags / tags tables and for performance reason we have entityWithTags table where 
tags are stored as array. This feature can really help us to remove all our owns triggers

Thanks!

**Comment by yugo-n** [comment]
Thank you for your comment! Your use case makes sense and I am interested in this. 

However,  the current implementation doesn't support this and we don't plan to support this in the patch targeting to PG13. In future, maybe we will work on this when extending aggregates support.

This is just a insight, I think one difficulty of supporting array_agg / json(b)_agg is maintaining the order of elements in arrays. If we allow the order changes when a base table is modified, this would be a bit easier.

**Comment by salacr** [comment]
Sure I just wan't to inform you about our use case. Even without the support this feature is really HUGE so thanks for a good work. I thought that it will be quite easy (actually much easier then for example AVG), but you are right that I forgot that this functions support ordering. In our use case we don't need that but I see your point.
Thanks!
