### ISSUE TITLE
SELECT statements with a TABLESAMPLE clause should be rejected.

### ISSUE THREAD

**Issue by nuko-yokohama** [sraoss/pgsql-ivm#80]
SELECT statements with a TABLESAMPLE clause should be rejected.

Currently, CREATE INCREMENTAL MATERIALIZED VIEW allows SELECT statements with the TABLESAMPLE clause.
However, the result of this SELECT statement is undefined and should be rejected when specified in CREATE INCREMENTAL MATERIALIZED VIEW.
(similar to handling non-immutable functions)

**Comment by thoshiai** [comment]
Thank you for your pointing out this issue.
it was fixed a short time ago. Please close this issue if there is no problem.

**Comment by nuko-yokohama** [comment]
Commit ID = b2e620958da6a6f402c4a64389f730f510746281 Version confirmed that the problem was fixed (reject SELECT with TABLE SAMPLE).
This issue closes.
